# TOML configuration file for parKVFinder software.

title = "parKVFinder parameters file"

[FILES_PATH]
# The path of van der Waals radii dictionary for parKVFinder.
dictionary = "/home/jvsguerra/KVpaper/KVFinder/linux/dictionary"
# The path of the input PDB file.
pdb = "/home/jvsguerra/KVpaper/KVFinder/linux/input/KV_Files/output/output.KVFinder.input.pdb"
# The path of the output directory.
output = "/home/jvsguerra/KVpaper/KVFinder/linux/input"
# Base name for output files.
base_name = "output"
# The path for the ligand's PDB file.
ligand = "/home/jvsguerra/KVpaper/KVFinder/linux/input/KV_Files/output/ligand_output_outpu.KVFinder.input.pdb"

[SETTINGS]
# Settings for parKVFinder software

	[SETTINGS.modes]
	# Whole protein mode defines the search space as the whole protein.
	whole_protein_mode = true
	# Box adjustment mode defines the search space as the box drawn in PyMOL.
	box_mode = false
	# Resolution mode implicitly sets the step size (grid spacing) of the 3D grid.
	# If set to High, sets a voxel volume of 0.2. If set to Medium, sets a voxel volume of 0.1. If set to Low, it sets a voxel volume of 0.01. If set to Off, the step size must be set explicitly.
	resolution_mode = "Low"
	# Surface mode defines the type of surface representation to be applied, van der Waals molecular surface (true) or solvent accessible surface (false).
	surface_mode = true
	# Cavity output mode defines whether cavities are exported to the output PDB file as filled cavities (true) or filtered cavities (false).
	kvp_mode = false
	# Ligand adjustment mode defines the search space around the ligand.
	ligand_mode = true

	[SETTINGS.step_size]
	# Sets the 3D grid spacing. It directly affects accuracy and runtime.
	step_size = 0.0

	[SETTINGS.probes]
	# parKVFinder works with a dual probe system. A smaller probe, called Probe In, and a bigger one, called Probe Out, rolls around the protein.
	# Points reached by the Probe In, but not the Probe Out are considered cavity points.
	# Sets the Probe In diameter. Default: 1.4 angstroms.
	probe_in = 1.4
	# Sets the Probe Out diameter. Default: 4.0 angstroms.
	probe_out = 4.0

	[SETTINGS.cutoffs]
	# Sets a volume cutoff for the detected cavities. Default: 5.0 angstroms.
	volume_cutoff = 5.0
	# Sets a distance cutoff for a search space around the ligand in ligand adjustment mode. Default: 5.0 angstroms.
	ligand_cutoff = 5.0
	# Sets a removal distance for the cavity frontier, which is defined by comparing Probe In and Probe Out surfaces. Default: 2.4 angstroms.
	removal_distance = 2.4

	[SETTINGS.visiblebox]
	# Coordinates of the vertices that define the visible 3D grid. Only four points are required to define the search space.
	bP1 = {bX1 = 0.00, bY1 = 0.00, bZ1 = 0.00}
	bP2 = {bX2 = 0.00, bY2 = 0.00, bZ2 = 0.00}
	bP3 = {bX3 = 0.00, bY3 = 0.00, bZ3 = 0.00}
	bP4 = {bX4 = 0.00, bY4 = 0.00, bZ4 = 0.00}

	[SETTINGS.internalbox]
	# Coordinates of the internal 3D grid. Used for calculations.
	P1 = {X1 = -4.00, Y1 = -4.00, Z1 = -4.00}
	P2 = {X2 = 4.00, Y2 = -4.00, Z2 = -4.00}
	P3 = {X3 = -4.00, Y3 = 4.00, Z3 = -4.00}
	P4 = {X4 = -4.00, Y4 = -4.00, Z4 = 4.00}
